services:
  api:
    image: clue:local
    ports:
      - "8080:8080"

  frontend:
    image: python:3.12-slim
    working_dir: /app/front
    volumes:
      - ./front/dist:/app/front
    ports:
      - "8081:8081"
    command: python3 -m http.server 8081

  docs:
    image: squidfunk/mkdocs-material
    volumes:
      - .:/docs
    ports:
      - "8082:8000"
