site_name: Clue
theme: 
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  # Palette toggle for dark mode
    - scheme: slate
      primary: deep-purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
